language: cpp
compiler:
- gcc
- clang
script: ./autogen.sh && ./configure --enable-coverage && make test
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
before_script:
- ./utils/build_gtest.sh
- gem install coveralls-lcov
after_success:
- make coverage.info
- coveralls-lcov coverage.info
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && make
  deploy-docs
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - gcc-4.8
    - g++-4.8
    - clang
    - doxygen
    - lcov
env:
  global:
  - secure: TnPeBWy3uDcXK4cPAxw8DXQxk1/DANU9cxMgqNGQBXEswLqyKw4iVanN0nTbGNj8F8YUblesLb5liUeTbNNS3F4xP087//7JuGOWiXJpUvsP6irnvUab6R+GiTK9/K8VLZQFM0s+Wr8fD3UZ6UbbLmK7Q99eMDSEif3ANZP0gEvPqqX7XAa6WOIKryVMIqGHUrQLDG3478dFuCd/iH6Nc81uVSA8ej0V6MJduP5/dQn7zuJ6IKt4DfpQso1cMgTLdirma/KwaEh0E7V3ZQWywzDza4Vf/yNc9Mc+GNq15sCDfsaR3APs3oktbuUo8aeeYYnVv4ZJUjN5vkLuUg8gPhwD/IeZuCbTx7YdIE/pGezvcggnQSwhTGMMYv41ceX3LS5LOUc7Jy/pW28/MHGTyvnJAkq9AmbHbmIEsS/k+r0Ou5uxk5OzdzpBt3dY44BbMg+UwmOu7rR5Rw4F9sy9B+SYGYWPINN6cF/Pdqc0Md8VhyABGl7cWWoKkeMx+uGoSflb7QYASmRPgyzTY6xLokGS/Tiuq4FKS23zGVR6citrPFJOohmgVXwkA6FeoK9mxIweqsQ176xwuOX/kntz/7tJ0uFv0P+bPcnm8NJqfY3NNezO0tcbyDEe+WDDNip//x/A5JivXWfR6+OSiq+hAYFDJEKhRIa1Shq0SHozpXY=
  - secure: FgxJmWoB5hFCnLwjfNMLUfWwnVNOer2aQhTn5rDsfpGW1xl/hnlBuvvqOYQ7T/ihFqwcecsPSi9z65NbnCVChyfVVGyAcO3WDxOfC2WK+NRx1Cqx8LZ74lyCSWyd22t0WMc/mf0bAVAMrVRxSLEpSLbVTe4BhI1FhG7NgFk38MBZniW/da9fBor8zYL0EImcxTeIlRSV9jNIbGxaq5+NfUq3Br96LlINs7SfBtILyMMMRt6vgz6XCWnn+Q+Mfnr/N1ak6RRVR3cGHdPekbkJhrJ6pmtcC3tGAqqpIWMbn4BemlFBhZEn71LpVew/ucN4SPY+2zLS+7WgEanwI1K2ults51w5hDMgpefKIv5ql87LfeEHxP95eiBbE9L06K706QfYQsDJ5JXTO23/HkA6cefY5k8MD/tuD+o01RRnWIJgbLYhC9/QRqL8FQD8nuSmDeviARXmpvxRkF5/NfKgQ7+1Cx8G0vKuH809JvI9yuiLVBiLE/ujxbhg3Kji1rR1/MIyOxiDqnhxEpWMdmlflBJy67cjygwPUZKm6mCsqw1zGP3dD7G9Mj2Vbnk3qP90S43PNHxirIzM7sc8+Sr0MBnoyj+F4KgfAFKjJVz1ZzQ4ZWcoCh784j5CviR0ODq3P4RHLsUcv0BLFH2aGB8xdkw7cfIkVgzEzdX2XW9/u58=
