language: cpp
compiler: g++
script: ./autogen.sh && ./configure && make test
before_script:
  - ./utils/build_gtest.sh
  - export CXX="g++-4.8"
sudo: false
addons:
  apt:
    packages:
    - build-essential
    - g++-4.8

